name: CI
on:
    push:
        branches:
            - main
    workflow_dispatch:
  
jobs:
    run-linker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: blog.sh
              shell: bash
              run: ./.ci/blog.sh/run.sh

            - name: Run Linker
              shell: bash
              run: ./.ci/linker/run.sh

            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Commit & Push changes
              uses: actions-js/push@master
              with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    author_name: Not-a-bot
                    message: CI
                    branch: main
